name: Auto Add PR to Project

on:
  pull_request:
    types: [opened]

jobs:
  add_pr_to_project:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Fetch linked projects for the repository
      - name: Get Linked Project Name
        id: get_project
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.inertia-preview+json" \
                        https://api.github.com/repos/${{ github.repository }}/projects)
          
          project_name=$(echo "$response" | jq -r '.[0].name')

          if [[ "$project_name" == "null" ]]; then
            echo "No project linked to this repository"
            exit 1
          else
            echo "Project found: $project_name"
            echo "::set-output name=project_name::$project_name"
          fi

      # Step 2: Add the PR to the project, if found
      - name: Add PR to Project Board
        if: steps.get_project.outputs.project_name != ''
        uses: actions-ecosystem/action-add-project-card@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_name: ${{ steps.get_project.outputs.project_name }}
          column_name: 'In Review'

      # Step 3: Optionally, add a sprint label
      - name: Add Sprint Label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label 'sprint-12'
